name: Check for Specific Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  find-comment-and-check:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null  # Ensures it's a PR comment

    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: "search string 1"

      - name: Check if comment was found
        run: |
          if [[ "${{ steps.fc.outputs.comment-id }}" == "" ]]; then
            echo "Comment not found. Failing the workflow."
            exit 1
          else
            echo "Comment found."
            echo "Comment ID: ${{ steps.fc.outputs.comment-id }}"
            echo "Comment Body: ${{ steps.fc.outputs.comment-body }}"
            echo "Comment Author: ${{ steps.fc.outputs.comment-author }}"
            echo "Comment Created At: ${{ steps.fc.outputs.comment-created-at }}"
          fi
