name: "Check PR checklist comment added"

on:
  issue_comment:
    types: [created]

jobs:
  comment-check:
    env:
      PR_CHECKLIST_KEYWORD: 'pr checklist reviewed'  # Set your checklist keyword here
      
    runs-on: ubuntu-latest

    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 1
          body-includes: pr checklist reviewed
